version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - ${MYSQL_PORT_INFO}
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${USER_NAME}
      - MYSQL_PASSWORD=${USER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - TZ:Asia/Seoul
    volumes:
      - ${DB_VOLUME_PATH}
      - ${DB_INITDB_PATH}

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT_INFO}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_PATH}:/usr/local/etc/redis/redis.conf

  openvidu:
    image: openvidu/openvidu-server-kms
    container_name: openVidu
    restart: always
    ports:
      - 14443:4443
    environment:
      - OPENVIDU_SECRET=1234
      - openvidu.publicurl=https://localhost:4443

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: my-es-container
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    container_name: my-kibana-container
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
